# SPDX-FileCopyrightText: © 2026 hashcatHitman
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[build]
# Comment out when working on rust-lang/rust-clippy (link-arg breaks the build)
rustflags = ["-Ctarget-cpu=native", "-Clink-arg=-fuse-ld=mold"]

# Uncomment if working on nightly toolchain
# rustflags = ["-Ctarget-cpu=native", "-Clink-arg=-fuse-ld=mold", "-Zthreads=32"]

[net]
git-fetch-with-cli = true

[profile.release]
codegen-units = 1
strip = true
opt-level = 3
debug = false
lto = true
incremental = false

[profile.release.package."*"]
codegen-units = 1
strip = true
opt-level = 3
debug = false
incremental = false

[profile.release.build-override]
codegen-units = 1
strip = true
opt-level = 3
debug = false
incremental = false
