# SPDX-FileCopyrightText: © 2026 hashcatHitman
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.squidowl.org/configuration/index.html

[servers.oftc]
nickname = "hashcatHitman"
nick_password_keyring = true
nick_identify_syntax = "password-nick"
username = "hashcatHitman/oftc"
server = "bnc.thunderirc.net"
port = 31337
password_keyring = true
channels = ["#tor", "#tor-project", "#tor-dev", "#tor-onions"]

[servers.oftc.irc_protocol_log]
enabled = true
timestamp = "utc"

[buffer.timestamp]
format = "%Y/%m/%d %r"

[font]
size = 13
weight = "normal"
