# SPDX-FileCopyrightText: © 2026 hashcatHitman
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[username]
format = "[$user]($style)@"
show_always = true

[hostname]
format = "[$ssh_symbol$hostname]($style) in "
ssh_only = false
trim_at = ""

[sudo]
disabled = false
