# SPDX-FileCopyrightText: © 2026 hashcatHitman
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[[language]]
name = "rust"
indent = { tab-width = 4, unit = "    " }
formatter = { command = "rustfmt" }
